version: 3.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: dotnet restore src/GoldenEye.sln
build:
  project: src/GoldenEye.sln
  verbosity: minimal
services:
  - mssql2016
